print("NHẬP HỒ SƠ BỆNH NHÂN ")
ma_benh_nhan = input("Nhập mã bệnh nhân :")
nhip_tim = int(input("Nhập nhịp tim đo được :"))
nhiet_do = float(input("Nhập nhiệt độ cơ thể "))
print("----- KẾT QUẢ CHUẨN HÓA DỮ LIỆU -----")
print("Mã bệnh nhân :",ma_benh_nhan)
print("Nhịp tim :",nhip_tim)
print("Kiểu dữ liệu hệ thống ghi nhận là : " ,type(nhip_tim))
print("Nhiệt độ cơ thể :",f"{nhiet_do} độ C" )
print("Kiểu dữ liệu hệ thống ghi nhận là : ", type(nhiet_do))
print("Thông báo : Dữ liệu hợp lệ . Màn hình Monitor đã sẵn sàng kết nối !")
