print("Vui lòng nhập thông tin bệnh nhân : ")
ten = str(input(" Nhập họ và tên bệnh nhân :"))
nam_sinh = int(input(" Nhập năm sinh bệnh nhân :"))
gioi_tinh = str(input(" Nhập giới tính bệnh nhân :"))
email = str(input(" Nhập email :"))
sdt = str(input(" Nhập số điện thoại liên hệ :"))
trieu_chung = str(input(" Nhập triệu chứng ban đầu :"))
chi_phi = float(input(" Nhập chi phí khám:"))

print("-----PHIẾU KHÁM BỆNH-----")
print("Mã bệnh nhân :",f"BN{ten}{nam_sinh}123")
print("Tên bệnh nhân :"f"{ten}(str)")
print("Năm sinh :",f"{nam_sinh}(int)")
print("Giới tính :",f"{gioi_tinh}(str)")
print("email :",f"{email}(str)")
print("Số điện thoại :",f"{sdt}(str)")
print("Triệu chứng ban đầu :",f"{trieu_chung}(str)")
print("Chi phí khám :",f"{chi_phi}(float) ")

